
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 06 01:47:54 CET 2012
//----------------------------------------------------

package org.microjava.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 23;
  public static final int DIVIDE = 3;
  public static final int NOTEQUAL = 10;
  public static final int LPAREN = 18;
  public static final int GREATER = 11;
  public static final int SEMI = 8;
  public static final int INVALID = 38;
  public static final int LESS = 13;
  public static final int MINUS = 6;
  public static final int RPAREN = 17;
  public static final int AND = 36;
  public static final int LESSEQUAL = 14;
  public static final int OR = 35;
  public static final int COMMA = 7;
  public static final int CLASS = 25;
  public static final int PLUS = 5;
  public static final int ASSIGN = 15;
  public static final int IF = 28;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 24;
  public static final int RETURN = 32;
  public static final int EQUAL = 9;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int NUMBER = 39;
  public static final int MOD = 4;
  public static final int IDENT = 41;
  public static final int BREAK = 31;
  public static final int VOID = 27;
  public static final int GREATEREQUAL = 12;
  public static final int TIMES = 2;
  public static final int LBRACE = 19;
  public static final int ELSE = 29;
  public static final int LSQUARE = 21;
  public static final int READ = 33;
  public static final int CHARCONST = 40;
  public static final int RSQUARE = 22;
  public static final int FINAL = 26;
  public static final int WHILE = 30;
  public static final int RBRACE = 20;
  public static final int PRINT = 34;
}

