
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 08 19:51:08 CET 2012
//----------------------------------------------------

package org.microjava.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 22;
  public static final int DIVIDE = 3;
  public static final int NOTEQUAL = 9;
  public static final int LPAREN = 17;
  public static final int GREATER = 10;
  public static final int SEMI = 8;
  public static final int INVALID = 37;
  public static final int LESS = 12;
  public static final int MINUS = 6;
  public static final int RPAREN = 16;
  public static final int AND = 35;
  public static final int LESSEQUAL = 13;
  public static final int OR = 34;
  public static final int COMMA = 7;
  public static final int CLASS = 24;
  public static final int PLUS = 5;
  public static final int ASSIGN = 14;
  public static final int IF = 27;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 23;
  public static final int RETURN = 31;
  public static final int EQUAL = 41;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int NUMBER = 38;
  public static final int MOD = 4;
  public static final int IDENT = 40;
  public static final int BREAK = 30;
  public static final int VOID = 26;
  public static final int GREATEREQUAL = 11;
  public static final int TIMES = 2;
  public static final int LBRACE = 18;
  public static final int ELSE = 28;
  public static final int LSQUARE = 20;
  public static final int READ = 32;
  public static final int CHARCONST = 39;
  public static final int RSQUARE = 21;
  public static final int FINAL = 25;
  public static final int WHILE = 29;
  public static final int RBRACE = 19;
  public static final int PRINT = 33;
}

